language: java

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -yqq
  - sudo apt-get install -yqq python3 python3-pip

install:
  - sudo pip3 install pre-commit

script:
  - pre-commit run --all-files --verbose
  - mvn -q -f the-mathmos-parent/pom.xml clean package install -U -B
  - mvn -q -f the-mathmos-server/pom.xml --settings settings.xml clean test package install -U -B
